export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANY_OFFERS_SUCCESS = 'GET_COMPANY_OFFERS_SUCCESS';
export const GET_SELECTED_COMPANY_SUCCESS = 'GET_SELECTED_COMPANY_SUCCESS';
export const SET_SELECTED_OFFER_SUCCESS = 'SET_SELECTED_OFFER_SUCCESS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_USER_RESERVATIONS_SUCCESS = 'GET_USER_RESERVATIONS_SUCCESS';
